### ISSUE TITLE
TypeError: plot_pros() takes 5 positional arguments but 7 were given

### ISSUE THREAD

**Issue by teinhonglo** [jcvasquezc/DisVoice#14]
Thanks for this project.
I encounter some errors when i run ./test_prosody.sh
Could you tell me what plot function I should call at this line?
[prosody.py#L247](https://github.com/jcvasquezc/DisVoice/blob/master/prosody/prosody.py#L247)

Error Message:
Traceback (most recent call last):
  File "prosody.py", line 406, in <module>
    profeats = prosody_dynamic(audio_file)
  File "prosody.py", line 248, in prosody_dynamic
    plot_pros(data_audio, fs, F0, seg_voiced, Ev, featvec, f0v)

**Comment by jcvasquezc** [comment]
The bug is solved in the current version
