### ISSUE TITLE
FileNotFoundError working with Articulation Features

### ISSUE THREAD

**Issue by Sruthik22** [jcvasquezc/DisVoice#16]
Hi, I have pulled the latest version of this repository. I am having trouble extracting the articulation features from my own audio. I was able to successfully run all of the provided IPython Notebooks.

```
File "PycharmProjects/ML-Parkinson-Disease/DisVoice/articulation/articulation.py", line 251, in extract_features_file
F0,_=praat_functions.decodeF0(temp_filename_f0,len(data_audio)/float(fs),self.step)
File "PycharmProjects/ML-Parkinson-Disease/DisVoice/articulation/../praat/praat_functions.py", line 139, in decodeF0
if os.stat(fileTxt).st_size==0:

FileNotFoundError: [Errno 2] No such file or directory: 'PycharmProjects/ML-Parkinson-Disease/DisVoice/articulation/../tempfiles/tempF0articulationID17_pd__12_2_1_0.txt'
```

If it is relevant, I am running this script in my ML-Parkinson-Disease folder, which contains the DisVoice folder within it.

**Comment by CarmiShimon** [comment]
Hi, did you solve this issue?
Praat is popping windows still.
Any help would be great!

**Comment by pk2801** [comment]
Hello,
Did you get the solution for this issue?

**Comment by jeburks2** [comment]
Seeing this same error - what was the resolution?

**Comment by jcvasquezc** [comment]
This is a problem with the Praat installation, 

When you install praat you ned to be sure that it is added to the PATH environment. 

You can test it if in a terminal you are able to run

On Windows

praat.exe --run

On Linux
praat

At the moment this is not supported for Mac devices

**Comment by jeburks2** [comment]
Thanks @jcvasquezc ! We are running this through SBATCH scripts on a GUI-less supercomputer, so we have the 'no-GUI server edition' of praat installed. Looks like praat has to be called as "praat --run" rather than "praat" to function without a GUI. 

Made the change on lines 44 and 68 of of praat_functions.py and seems to be working fine now for our environment. Hopefully this helps someone else too. Thanks!

**Comment by jcvasquezc** [comment]
This has been solved in the latest version of the tool

Thanks for the issue
