### ISSUE TITLE
`calc_residual(x_filt,x_emph,...)` instead of `calc_residual(x_filt,x_filt,...)`?

### ISSUE THREAD

**Issue by waynezv** [jcvasquezc/DisVoice#18]
https://github.com/jcvasquezc/DisVoice/blob/9bda5815df9b05daf329e012379d36f07122f7cc/glottal/GCI.py#L147

In _Line 142_ an **x_emph** is calculated, but it is never used thereafter. Shouldn't it be used in the subsequent lpc-filter process in _Line 147_? i.e.,

`calc_residual(x_filt,x_filt,...)` -> `calc_residual(x_filt,x_emph,...)`

**Comment by jcvasquezc** [comment]
Thanks for finding the bug
This is already fixed in the current version
