### ISSUE TITLE
import disvoice throws error ModuleNotFoundError: No module named 'disvoice.glottal.glottal'

### ISSUE THREAD

**Issue by macaylad** [jcvasquezc/DisVoice#52]
I assume this is because something went wrong during install, but I'm not sure what.

**Comment by alaaNfissi** [comment]
I have the same issue and I'm having this too: 
![image](https://user-images.githubusercontent.com/35638517/210907412-d3320192-a1aa-4eb5-8300-70b2eddc72d9.png)

**Comment by chaufanglin** [comment]
I have the same issue and adding KALDI_ROOT can't solve it.

**Comment by spandandey21** [comment]
disvoice.glottal.Glottal --> it works for me. See the folders and .py file names.
