### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by eunjung31** [jcvasquezc/DisVoice#57]
I think this line should return pd.DataFrame(dff) instead of pd.DataFrame(df).

https://github.com/jcvasquezc/DisVoice/blob/6e88fcc3dd18d2ee3177133b2c76d07e7e2d5866/disvoice/phonological/phonological.py#L133C1-L134C1

**Comment by jcvasquezc** [comment]
Thanks
This was already fixed in the last PR
